map "$host:$http_x_forwarded_proto" $redirect_to_https {
    default 0;
    "xattax.cloudlane.com.br:http" 1;
}

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    if ($redirect_to_https) {
        return 301 https://xattax.cloudlane.com.br$request_uri;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
