import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowUpRight, ArrowDown, ArrowUp, Menu, X, MessageCircle, Layers3, FileText, UserRound, BriefcaseBusiness, Plus, MapPin, Building2, Check, Mail } from 'lucide-react'
import { motion, useReducedMotion } from 'motion/react'
import { contact, contactUrl, services, faqs } from './content'
import { Contact } from './Contact'
import { assetUrl } from './assets'
import './App.css'

function Brand() { return <a className="brand" href="#inicio" aria-label="XattaX, início"><img src={assetUrl('brand/xattax-logo.svg')} width="588" height="392" alt="XattaX — Escritório de apoio imobiliário e contábil" /></a> }
function Reveal({ children, className = '' }: { children: ReactNode, className?: string }) {
  const reduced = useReducedMotion()
  return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .08 }} transition={{ duration: reduced ? 0 : .55 }}>{children}</motion.div>
}
function Clarity() {
  const [organized, setOrganized] = useState(true)
  const reduced = useReducedMotion()
  return <div className={`clarity ${organized ? 'organized' : ''}`}>
    <div className="clarity-top"><span>UM NOVO OLHAR PARA O SEU DIA A DIA</span><Layers3 size={20} aria-hidden="true" /></div>
    <div className="composition" aria-hidden="true">{Array.from({ length: 7 }, (_, i) => <motion.div className="plane" key={i} animate={{ x: organized ? 0 : [32, -40, 24, -30, 40, -15, 0][i], y: i * -19, rotate: organized ? -28 : [-45, 8, -38, 10, -20, 4, -28][i] }} transition={{ duration: reduced ? 0 : .8, type: 'tween', ease: [.22, 1, .36, 1] }} style={{ zIndex: i + 1, opacity: .42 + i * .08 }}>{i === 6 && <img className="plane-logo" src={assetUrl('brand/xattax-mark-light.svg')} width="588" height="360" alt="" />}</motion.div>)}</div>
    <div className="art-caption"><span className="art-cross" aria-hidden="true">+</span><p>Quando tudo se conecta,<br /><strong>o próximo passo fica mais claro.</strong></p></div>
    <div className="clarity-bottom"><button onClick={() => setOrganized(!organized)} aria-label="Organizar composição" aria-pressed={organized}><span className="toggle-track" aria-hidden="true"><span /></span><span aria-live="polite">{organized ? 'Tudo em seu lugar' : 'Encontre a clareza'}</span></button><span>INTERAJA ↗</span></div>
    <p className="concept-note">Composição conceitual · sem dados financeiros</p>
  </div>
}
function Services() {
  const [expanded, setExpanded] = useState<number | null>(null)
  const icons = [FileText, UserRound, BriefcaseBusiness, MessageCircle]
  return <section className="wrap section services" id="servicos" aria-labelledby="services-heading"><Reveal><p className="eyebrow">01 / EM QUE PODEMOS AJUDAR</p><div className="section-heading"><h2 id="services-heading">Cada necessidade,<br /><span>um ponto de partida.</span></h2><p>Para você e para o seu negócio.<br />Encontre o assunto que trouxe você até aqui.</p></div></Reveal><div className="service-grid">{services.map((service, i) => { const Icon = icons[i]; return <article key={service.title} className={`service-card ${expanded === i ? 'expanded' : ''}`}><div className="service-top"><Icon size={24} strokeWidth={1.4} aria-hidden="true" /><span>0{i + 1}</span></div><p className="service-tag">{service.tag}</p><h3>{service.title}</h3><p>{service.description}</p><button className="service-disclosure" onClick={() => setExpanded(expanded === i ? null : i)} aria-expanded={expanded === i} aria-controls={`service-${i}`}>{expanded === i ? 'Fechar detalhes' : 'Conhecer o serviço'}<Plus size={18} aria-hidden="true" /></button><div className="service-detail" id={`service-${i}`} hidden={expanded !== i}><p>{service.detail}</p><a href={contactUrl(`Olá, XattaX! Gostaria de conversar sobre ${service.title.toLowerCase()}.`)} target="_blank" rel="noopener noreferrer">Conversar sobre este serviço <ArrowUpRight size={16} /></a></div></article> })}</div><div className="property-strip"><div className="property-title"><Building2 size={27} strokeWidth={1.4} aria-hidden="true" /><h3>Também precisa de apoio imobiliário?</h3></div><p>Conte sua necessidade e consulte as possibilidades de atendimento.</p><a className="text-link" href={contactUrl('Olá, XattaX! Gostaria de conhecer o apoio imobiliário disponível.')} target="_blank" rel="noopener noreferrer">Vamos conversar <ArrowUpRight size={18} /></a></div></section>
}
function App() {
  const [menu, setMenu] = useState(false)
  const [active, setActive] = useState('inicio')
  const [privacy, setPrivacy] = useState(false)
  const menuRef = useRef<HTMLButtonElement>(null)
  const dialogRef = useRef<HTMLDialogElement>(null)
  const privacyTrigger = useRef<HTMLButtonElement>(null)
  useEffect(() => { const listener = (e: KeyboardEvent) => { if (e.key === 'Escape' && menu) { setMenu(false); menuRef.current?.focus() } }; document.addEventListener('keydown', listener); return () => document.removeEventListener('keydown', listener) }, [menu])
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { for (const entry of entries) if (entry.isIntersecting) setActive(entry.target.id) }, { rootMargin: '-15% 0px -55% 0px', threshold: 0 })
    document.querySelectorAll('main section[id]').forEach(section => observer.observe(section))
    return () => observer.disconnect()
  }, [])
  useEffect(() => {
    if (privacy) { dialogRef.current?.showModal(); document.body.style.overflow = 'hidden' }
    else { if (dialogRef.current?.open) dialogRef.current.close(); document.body.style.overflow = '' }
    return () => { document.body.style.overflow = '' }
  }, [privacy])
  function closePrivacy() { setPrivacy(false); privacyTrigger.current?.focus() }
  return <>
    <a className="skip" href="#conteudo">Pular para o conteúdo</a>
    <header className="header"><div className="wrap header-inner"><Brand /><nav className={menu ? 'nav open' : 'nav'} id="navigation" aria-label="Navegação principal">{[['sobre', 'A XattaX'], ['servicos', 'Serviços'], ['como-funciona', 'Como funciona']].map(([id, label]) => <a key={id} href={`#${id}`} aria-current={active === id ? 'location' : undefined} onClick={() => setMenu(false)}>{label}</a>)}<a className="mobile-contact" href="#contato" onClick={() => setMenu(false)}>Vamos conversar</a></nav><a className="header-contact" href="#contato">Fale com a XattaX <ArrowUpRight size={17} /></a><button ref={menuRef} className="menu-toggle" aria-label={menu ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div></header>
    <main id="conteudo"><section id="inicio" className="hero wrap" aria-labelledby="hero-heading"><div className="hero-copy"><p className="eyebrow"><span className="mini-line" /> APOIO CONTÁBIL & IMOBILIÁRIO</p><h1 id="hero-heading">Menos dúvidas.<br />Mais clareza.<br /><span>Novos caminhos.</span></h1><p className="hero-description">Da sua declaração ao próximo passo do seu negócio. Converse com a XattaX sobre o apoio que você precisa.</p><div className="hero-actions"><a className="button primary" href="#contato">Fale com a XattaX <ArrowUpRight size={19} /></a><a className="text-link" href="#servicos">Conheça nossos serviços <ArrowDown size={17} /></a></div><div className="hero-location"><span>CAMPO GRANDE, MS</span><span>Uma conversa é um bom começo.</span></div></div><Clarity /></section><div className="ribbon"><div className="wrap"><span>CLAREZA PARA DECIDIR</span><span aria-hidden="true">✳</span><span>APOIO PARA SEGUIR</span><span aria-hidden="true">✳</span><span>CONVERSAS QUE APROXIMAM</span></div></div>
      <Services />
      <section className="about-section section" id="sobre" aria-labelledby="about-heading"><div className="wrap"><Reveal className="about-grid"><div className="about-manifesto"><p className="eyebrow">02 / A XATTAX</p><h2 id="about-heading">Por trás de<br />cada número,<br /><span>existe uma<br />história.</span></h2><div className="about-origin"><img src={assetUrl('brand/xattax-logo-light.svg')} width="588" height="392" alt="Logo da XattaX" loading="lazy" /><span>XattaX<br /><small>Apoio imobiliário e contábil</small></span></div></div><div className="about-copy"><span className="large-plus" aria-hidden="true">+</span><h3>O seu contexto é o<br />começo da conversa.</h3><p>A XattaX é um escritório de apoio imobiliário e contábil em Campo Grande, Mato Grosso do Sul.</p><p>Se a sua dúvida é sobre uma declaração, uma pendência ou os próximos passos do seu negócio, apresente sua necessidade. Consulte a equipe para entender o apoio disponível para você.</p><a className="text-link" href="#contato">Conte o que você precisa <ArrowUpRight size={18} /></a></div></Reveal><div className="bento"><div className="bento-local"><MapPin size={23} strokeWidth={1.5} /><div><span>DE CAMPO GRANDE</span><h3>Um endereço.<br /> Uma conexão real.</h3><p>{contact.address}</p></div></div><div className="bento-areas"><Layers3 size={23} strokeWidth={1.5} /><span>ÁREAS QUE SE CONECTAM</span><h3>Contábil.<br /> Imobiliário.</h3><p>Consulte o apoio para a sua necessidade.</p></div><div className="bento-direct"><MessageCircle size={23} strokeWidth={1.5} /><span>CONVERSA DIRETA</span><h3>Do seu jeito.<br /> Pelo WhatsApp.</h3><a href={contactUrl('Olá, XattaX! Gostaria de conhecer o atendimento.')} target="_blank" rel="noopener noreferrer">Iniciar uma conversa <ArrowUpRight size={17} /></a></div></div></div></section>
      <section className="wrap section journey" id="como-funciona" aria-labelledby="journey-heading"><Reveal><p className="eyebrow">03 / SEM COMPLICAR O PRIMEIRO PASSO</p><div className="section-heading"><h2 id="journey-heading">Comece com um oi.<br /><span>Continue com clareza.</span></h2><p>Uma forma simples de preparar seu contato.<br />Os detalhes são combinados com a equipe.</p></div></Reveal><ol className="steps">{[['Escolha o assunto', 'Selecione o motivo do contato. Pode ser uma dúvida específica ou apenas vontade de conhecer a XattaX.'], ['Conte o seu momento', 'Revise a mensagem no WhatsApp e explique, com suas palavras, o que você precisa.'], ['Converse sobre os próximos passos', 'Consulte disponibilidade, escopo, documentos, valores e prazos antes de decidir.']].map(([title, text], i) => <li key={title}><span className="step-index">0{i + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><div className="journey-note"><Check size={17} /> Você não precisa enviar documentos ou dados financeiros para começar por aqui.</div></section>
      <section className="faq-section" id="duvidas" aria-labelledby="faq-heading"><div className="wrap faq-grid"><div><p className="eyebrow">04 / PERGUNTAS FREQUENTES</p><h2 id="faq-heading">Antes do<br />primeiro oi.</h2><p>Um pouco mais de clareza<br />para começar.</p></div><div className="faq-list">{faqs.map(([q, a], i) => <details key={q}><summary><span className="faq-number">0{i + 1}</span><span>{q}</span><Plus size={19} aria-hidden="true" /></summary><p>{a}</p></details>)}</div></div></section>
      <Contact />
    </main><footer className="wrap footer"><div className="footer-top"><Brand /><span>Apoio contábil e imobiliário.<br />Campo Grande, MS.</span><a href="#inicio">Voltar ao início <ArrowUp size={17} /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} XattaX. Todos os direitos reservados.</span><div><a href={`mailto:${contact.email}`} aria-label="Enviar e-mail à XattaX"><Mail size={16} /></a><button ref={privacyTrigger} onClick={() => setPrivacy(true)}>Privacidade</button><a href={contact.instagram} target="_blank" rel="noopener noreferrer">Instagram <ArrowUpRight size={14} /></a></div></div></footer><a className="floating" href={contactUrl('Olá, XattaX! Gostaria de conversar sobre o atendimento.')} target="_blank" rel="noopener noreferrer" aria-label="Conversar com a XattaX no WhatsApp"><MessageCircle size={23} /></a>
    <dialog ref={dialogRef} className="privacy-dialog" aria-labelledby="privacy-heading" onCancel={closePrivacy} onClose={() => setPrivacy(false)}><button className="dialog-close" onClick={closePrivacy} aria-label="Fechar privacidade"><X /></button><p className="eyebrow">SUA PRIVACIDADE</p><h2 id="privacy-heading">Uma conversa,<br />no seu tempo.</h2><p>Este site não recebe documentos, não solicita dados financeiros e não armazena a seleção de assunto depois que a página é fechada. Não adicionamos ferramentas de publicidade ou análise de visitantes.</p><p>Ao continuar no WhatsApp, a mensagem é aberta nesse serviço. Você decide se deseja enviá-la. WhatsApp e Instagram têm suas próprias políticas de privacidade. O link de e-mail abre seu aplicativo de e-mail.</p><p>Fontes são carregadas pelo Google Fonts. A hospedagem e os serviços externos podem tratar dados técnicos necessários para funcionar, como o endereço IP.</p><p>Para dúvidas sobre o tratamento de informações compartilhadas no atendimento, entre em contato com a XattaX: <a href={`mailto:${contact.email}`}>{contact.email}</a>.</p></dialog>
  </>
}
export default App

